stages:
  - build
  - release
build-binary:
  stage: build
  image: 'registry.office.cubits.com:5000/golang-build:v0.1'
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - make deps
    - make
